# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

  encoders:
    App\Entity\Account:
      algorithm: bcrypt
  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    our_db_provider:
      entity:
        class: App:Account
        property: username

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/

      # but the firewall does not require login on every page
      # denying access is done in access_control or in your controllers
      anonymous: true
      form_login:
        provider: our_db_provider
        login_path: login
        check_path: login
        always_use_default_target_path: true
        default_target_path: /home
        csrf_token_generator: security.csrf.token_manager
      logout:
        path:   logout
        target: login



  access_control:
  - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
  - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
  - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
  - { path: ^/, role: [ROLE_ADMIN,ROLE_USER], requires_channel: https }